services:
  - type: web
    name: potomitan
    env: node
    buildCommand: NODE_ENV=development npm install && npx vite build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
