services:
  - type: web
    name: potomitan-dynamic
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
